id: P9ADB8C4F
initial_creation_type: ocr
source_metadata:
  volumes:
    bc11114d414f40d7a5bde981c3f63b06:
      base_file: v001.txt
      image_group_id: I1PD95846
      title: དོན་དམ་པར་བསྟོད་པ།
      total_pages: 1539
      volume_number: 1
