id: D19F4E2F9
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2021-12-31T07:03:40+00:00'
last_modified: '2022-05-26T06:05:06.487525+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/a7eec5e12ddce18d0ed1dbb732a42cf48f94dd09/openpecha/formatters/hfml.py
source_metadata:
  base:
    319d:
      image_group_id: I1PD95846
      title: དོན་དམ་པར་བསྟོད་པ།
      total_pages: 1539
      order: 1
      base_file: 319d.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
